// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLscu9Y-Dnnj1VjYcPps6vGq3_6Ja47SQ',
    appId: '1:481578290479:web:d2c8f0de5e57ae26cee5da',
    messagingSenderId: '481578290479',
    projectId: 'housepal-7f13f',
    authDomain: 'housepal-7f13f.firebaseapp.com',
    storageBucket: 'housepal-7f13f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbscxtXCcCvRt8z4nzmsdw2nVejAzhTY',
    appId: '1:481578290479:android:e32c358bf51a6db9cee5da',
    messagingSenderId: '481578290479',
    projectId: 'housepal-7f13f',
    storageBucket: 'housepal-7f13f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiQtHPtF2EzHK1tjoVSpGBlEq7fXJV28',
    appId: '1:481578290479:ios:2f96756395931a66cee5da',
    messagingSenderId: '481578290479',
    projectId: 'housepal-7f13f',
    storageBucket: 'housepal-7f13f.firebasestorage.app',
    iosBundleId: 'com.example.housepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiiQtHPtF2EzHK1tjoVSpGBlEq7fXJV28',
    appId: '1:481578290479:ios:2f96756395931a66cee5da',
    messagingSenderId: '481578290479',
    projectId: 'housepal-7f13f',
    storageBucket: 'housepal-7f13f.firebasestorage.app',
    iosBundleId: 'com.example.housepal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLscu9Y-Dnnj1VjYcPps6vGq3_6Ja47SQ',
    appId: '1:481578290479:web:b6d34c12fe3f67bbcee5da',
    messagingSenderId: '481578290479',
    projectId: 'housepal-7f13f',
    authDomain: 'housepal-7f13f.firebaseapp.com',
    storageBucket: 'housepal-7f13f.firebasestorage.app',
  );
}
